network:
  version: 2
  renderer: networkd
  ethernets:
    ens33:
      addresses:
        - 192.168.68.131/24
      routes:
        - to: default
          via: 192.168.68.2
    ens37:
      addresses:
        - 192.168.100.10/24
      routes:
        - to: 192.168.100.0/24
          via: 192.168.68.2
          table: 101
      routing-policy:
        - from: 192.168.100.0/24
          to: 192.168.68.2
          table: 101
      nameservers:
        search: 
          - "ddp.is"
        addresses: 
          - 192.168.100.10
          - 8.8.8.8
